name: Build Appling

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch:
          - x64
          # - arm64
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            CMakeLists.txt
            assets/darwin
            assets/linux
            assets/win32
            assets/splash.png
          sparse-checkout-cone-mode: false


      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tetherto'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl ca-certificates build-essential git clang llvm lld pkg-config libgtk-4-dev clang-tools fuse file
          npm install --global bare-make
          npm install cmake-pear
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Build Linux AppImage
        run: |
          bare-make generate --platform linux --arch ${{ matrix.arch }}
          bare-make build

      - name: Find AppImage file
        id: find_file
        run: |
          APPIMAGE_PATH=$(find $GITHUB_WORKSPACE -name "*.AppImage" -type f | head -n 1)
          echo "APPIMAGE_PATH=$APPIMAGE_PATH" >> $GITHUB_OUTPUT
          echo "Found AppImage at: $APPIMAGE_PATH"

          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: pearpass-linux-${{ matrix.arch }}.AppImage
          path: ${{ env.APPIMAGE_PATH }}

  macos:
    runs-on: macos-14
    strategy:
      matrix:
        arch:
          - x64
          - arm64
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            CMakeLists.txt
            assets/darwin
            assets/linux
            assets/win32
            assets/splash.png
          sparse-checkout-cone-mode: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tetherto'

      - name: Install dependencies
        run: |
          npm install --global bare-make
          npm install cmake-pear
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE }}
          P12_PASSWORD: ${{ secrets.APPLE_P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.APPLE_PROVISIONING_PROFILE }}
          KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.provisionprofile
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Build macOS app
        run: |
          bare-make generate --platform darwin --arch ${{ matrix.arch }}
          bare-make build

      - name: Find App file
        id: find_file
        run: |
          APPIMAGE_PATH=$(find $GITHUB_WORKSPACE -name "*.app" -type f | head -n 1)
          echo "APPIMAGE_PATH=$APPIMAGE_PATH" >> $GITHUB_OUTPUT
          echo "Found app at: $APPIMAGE_PATH"

          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: pearpass-macos-${{ matrix.arch }}.app
          path: ${{ env.APPIMAGE_PATH }}

      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.provisionprofile

  release:
    runs-on: ubuntu-latest
    needs: [linux]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts/
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*
