name: Publish App on Merge to Test

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  CHANNEL_LINK: "pear://3goejdzrg3g1pccaqsdy4meq9yiid1wasx3fbsxxnzafhqt8qhry"

permissions:
  contents: read
  packages: read

jobs:
  publish-worker:
    runs-on: ["self-hosted", "Linux", "large"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@tetherto'
      - name: Install worker dependencies
        run: |
          npm install --install-links
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NOXTTON_BOT_PAT }}
      - name: Extract translations
        run: |
          npm run lingui:extract
          npm run lingui:compile
      - name: "Stage to channel"
        run: |
          echo "CHANNEL_LINK: ${CHANNEL_LINK}"
          pear stage --ignore .git --no-ask ${CHANNEL_LINK}
      - name: "Release latest version"
        run: |
          pear release ${CHANNEL_LINK}
          
